#!/usr/bin/env bash
#
# VisionForge cluster agent installer.
#
# Usage (on the worker machine):
#
#   curl -fsSL https://<platform>/api/agents/install.sh \
#     | VF_AGENT_TOKEN=<random-secret> VF_VENDOR=nvidia bash
#
# Environment:
#   VF_AGENT_TOKEN  required  bearer token the platform uses to call /info,
#                              /telemetry, /adopt. Generated by the UI wizard.
#   VF_VENDOR       required  one of: nvidia | rocm | cpu
#   VF_AGENT_PORT   optional  host port to expose (default 9443)
#   VF_AGENT_IMAGE  optional  override the image (e.g. for a private registry)
#   VF_NAME         optional  container name (default vf-agent)
#   REDIS_URL       optional  passed through to the agent for Celery broker
#
set -euo pipefail

: "${VF_AGENT_TOKEN:?VF_AGENT_TOKEN must be set (generated by the wizard)}"
: "${VF_VENDOR:?VF_VENDOR must be set (nvidia | rocm | cpu)}"

PORT="${VF_AGENT_PORT:-9443}"
NAME="${VF_NAME:-vf-agent}"
REDIS="${REDIS_URL:-}"

case "${VF_VENDOR}" in
  nvidia)
    IMAGE="${VF_AGENT_IMAGE:-visionforge/agent:nvidia}"
    # --gpus all requires the NVIDIA container toolkit on the host.
    GPU_FLAGS=(--gpus all)
    ;;
  rocm)
    IMAGE="${VF_AGENT_IMAGE:-visionforge/agent:rocm}"
    # ROCm exposes the GPU via /dev/kfd + /dev/dri and needs the host's
    # `video` (and on newer distros, `render`) groups.
    GPU_FLAGS=(--device=/dev/kfd --device=/dev/dri
               --security-opt seccomp=unconfined
               --group-add video --group-add render)
    ;;
  cpu)
    IMAGE="${VF_AGENT_IMAGE:-visionforge/agent:cpu}"
    GPU_FLAGS=()
    ;;
  *)
    echo "error: VF_VENDOR='${VF_VENDOR}' is not recognised (expected nvidia | rocm | cpu)" >&2
    exit 2
    ;;
esac

command -v docker >/dev/null 2>&1 || {
  echo "error: docker is not installed or not on PATH" >&2
  exit 3
}

echo "vf-agent installer"
echo "  image:  ${IMAGE}"
echo "  vendor: ${VF_VENDOR}"
echo "  port:   ${PORT}"

# Pull explicitly so a missing image surfaces a clear error before we exec docker run.
docker pull "${IMAGE}"

# Replace any existing container with the same name so reruns are idempotent.
if docker ps -a --format '{{.Names}}' | grep -qx "${NAME}"; then
  echo "removing existing container '${NAME}'..."
  docker rm -f "${NAME}" >/dev/null
fi

run_args=(
  -d --name "${NAME}" --restart unless-stopped
  -p "${PORT}:9443"
  -v vf-agent-state:/var/lib/vf-agent
  -e "VF_AGENT_TOKEN=${VF_AGENT_TOKEN}"
)
if [[ -n "${REDIS}" ]]; then
  run_args+=(-e "REDIS_URL=${REDIS}")
fi
run_args+=("${GPU_FLAGS[@]}" "${IMAGE}")

docker run "${run_args[@]}"

echo
echo "vf-agent is running on port ${PORT}."
echo "Return to the VisionForge UI and submit Step 2 of the cluster wizard."
