# Alembic configuration file
[alembic]
script_location = src/app/db/migrations
sqlalchemy.url = postgresql+psycopg2://%(POSTGRES_USER)s:%(POSTGRES_PASSWORD)s@%(POSTGRES_HOST)s:%(POSTGRES_PORT)s/%(POSTGRES_DB)s

[post_write_hooks]
# none
